[package]
name = "changers"
version = "0.1.0"
authors = ["Alexander Sawtschuk <sawtschuk.alex@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
git2 = "0.10"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
